### ISSUE TITLE
Returned types for HTMLDocument methods are not documented

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Dom#61] opened 2016-11-18 14:28 UTC
This means that PHPStorm (and presumably other IDEs) are unable to syntax-check common patterns like: 
```php
$domDoc->getElementById("your-name")->setValue("monkey");
```
Instead, they fire a warning that the referenced method is not found. 

Suspect the fix is to add the return types to the PhpGt/Dom versions of the methods?

**Comment by g105b** [comment] 2016-11-18 15:19
[`getElementById`](http://php.net/manual/en/domdocument.getelementbyid.php) is part of the internal DOMDocument class. In fact there isn't anywhere within the PhpGt Dom repository that defines a `getElementById` method... should it be the responsibility of this repo to write the docs for an internal PHP extension?

**Comment by g105b** [comment] 2016-11-18 15:49
Update: The problem _isn't_ that PhpGt/Dom isn't documenting the base classes; the problem is that PhpGt/Dom doesn't explicitly state that the returned type is the extended objects, such as `Gt\Dom\Element`, etc.

**Comment by g105b** [comment] 2016-11-19 10:44
Closing, tracked in #46 .

**Closed by g105b** 2016-11-19 10:44 UTC
